# Generated by Django 4.1.5 on 2023-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='rota_number',
            field=models.IntegerField(default=0),
        ),
    ]
