# Generated by Django 4.1.5 on 2023-01-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtatapp', '0003_alter_posada_posad_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shtat',
            name='object',
        ),
        migrations.RemoveField(
            model_name='shtat',
            name='objectfact',
        ),
        migrations.AddField(
            model_name='shtat',
            name='object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='object', to='shtatapp.object'),
        ),
        migrations.AddField(
            model_name='shtat',
            name='objectfact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='objectfact', to='shtatapp.object'),
        ),
    ]
